# Generated by Django 3.1.5 on 2021-04-26 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='publishers',
        ),
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(default='media/covers/not_image.png', upload_to='covers'),
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer', to='games.developer'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='games.publisher'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='generation',
            field=models.CharField(blank=True, choices=[('1st', 'First generation'), ('2nd', 'Second generation'), ('3rd', 'Third generation'), ('4th', 'Fourth generation'), ('5th', 'Fifth generation'), ('6th', 'Sixth generation'), ('7nd', 'Seventh generation'), ('8rd', 'Eighth generation'), ('9th', 'Ninth generation')], max_length=4, null=True),
        ),
    ]
